// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gtfs-realtime-MTARR.proto

package dev.katsute.onemta;

@SuppressWarnings("all")
abstract class MTARRProto {
  private MTARRProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(dev.katsute.onemta.MTARRProto.mtaRailroadStopTimeUpdate);
    registry.add(dev.katsute.onemta.MTARRProto.mtaRailroadCarriageDetails);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MtaRailroadStopTimeUpdateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:transit_realtime.MtaRailroadStopTimeUpdate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string track = 1;</code>
     * @return Whether the track field is set.
     */
    boolean hasTrack();
    /**
     * <code>optional string track = 1;</code>
     * @return The track.
     */
    java.lang.String getTrack();
    /**
     * <code>optional string track = 1;</code>
     * @return The bytes for track.
     */
    com.google.protobuf.ByteString
        getTrackBytes();

    /**
     * <code>optional string trainStatus = 2;</code>
     * @return Whether the trainStatus field is set.
     */
    boolean hasTrainStatus();
    /**
     * <code>optional string trainStatus = 2;</code>
     * @return The trainStatus.
     */
    java.lang.String getTrainStatus();
    /**
     * <code>optional string trainStatus = 2;</code>
     * @return The bytes for trainStatus.
     */
    com.google.protobuf.ByteString
        getTrainStatusBytes();
  }
  /**
   * Protobuf type {@code transit_realtime.MtaRailroadStopTimeUpdate}
   */
  public static final class MtaRailroadStopTimeUpdate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:transit_realtime.MtaRailroadStopTimeUpdate)
      MtaRailroadStopTimeUpdateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MtaRailroadStopTimeUpdate.newBuilder() to construct.
    private MtaRailroadStopTimeUpdate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MtaRailroadStopTimeUpdate() {
      track_ = "";
      trainStatus_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MtaRailroadStopTimeUpdate();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.katsute.onemta.MTARRProto.internal_static_transit_realtime_MtaRailroadStopTimeUpdate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.katsute.onemta.MTARRProto.internal_static_transit_realtime_MtaRailroadStopTimeUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.katsute.onemta.MTARRProto.MtaRailroadStopTimeUpdate.class, dev.katsute.onemta.MTARRProto.MtaRailroadStopTimeUpdate.Builder.class);
    }

    private int bitField0_;
    public static final int TRACK_FIELD_NUMBER = 1;
    private volatile java.lang.Object track_;
    /**
     * <code>optional string track = 1;</code>
     * @return Whether the track field is set.
     */
    @java.lang.Override
    public boolean hasTrack() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string track = 1;</code>
     * @return The track.
     */
    @java.lang.Override
    public java.lang.String getTrack() {
      java.lang.Object ref = track_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          track_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string track = 1;</code>
     * @return The bytes for track.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTrackBytes() {
      java.lang.Object ref = track_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        track_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRAINSTATUS_FIELD_NUMBER = 2;
    private volatile java.lang.Object trainStatus_;
    /**
     * <code>optional string trainStatus = 2;</code>
     * @return Whether the trainStatus field is set.
     */
    @java.lang.Override
    public boolean hasTrainStatus() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string trainStatus = 2;</code>
     * @return The trainStatus.
     */
    @java.lang.Override
    public java.lang.String getTrainStatus() {
      java.lang.Object ref = trainStatus_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          trainStatus_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string trainStatus = 2;</code>
     * @return The bytes for trainStatus.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTrainStatusBytes() {
      java.lang.Object ref = trainStatus_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        trainStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static dev.katsute.onemta.MTARRProto.MtaRailroadStopTimeUpdate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.katsute.onemta.MTARRProto.MtaRailroadStopTimeUpdate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.katsute.onemta.MTARRProto.MtaRailroadStopTimeUpdate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.katsute.onemta.MTARRProto.MtaRailroadStopTimeUpdate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.katsute.onemta.MTARRProto.MtaRailroadStopTimeUpdate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.katsute.onemta.MTARRProto.MtaRailroadStopTimeUpdate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.katsute.onemta.MTARRProto.MtaRailroadStopTimeUpdate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.katsute.onemta.MTARRProto.MtaRailroadStopTimeUpdate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.katsute.onemta.MTARRProto.MtaRailroadStopTimeUpdate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dev.katsute.onemta.MTARRProto.MtaRailroadStopTimeUpdate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.katsute.onemta.MTARRProto.MtaRailroadStopTimeUpdate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.katsute.onemta.MTARRProto.MtaRailroadStopTimeUpdate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dev.katsute.onemta.MTARRProto.MtaRailroadStopTimeUpdate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code transit_realtime.MtaRailroadStopTimeUpdate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:transit_realtime.MtaRailroadStopTimeUpdate)
        dev.katsute.onemta.MTARRProto.MtaRailroadStopTimeUpdateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dev.katsute.onemta.MTARRProto.internal_static_transit_realtime_MtaRailroadStopTimeUpdate_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dev.katsute.onemta.MTARRProto.internal_static_transit_realtime_MtaRailroadStopTimeUpdate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dev.katsute.onemta.MTARRProto.MtaRailroadStopTimeUpdate.class, dev.katsute.onemta.MTARRProto.MtaRailroadStopTimeUpdate.Builder.class);
      }

      // Construct using dev.katsute.onemta.MTARRProto.MtaRailroadStopTimeUpdate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        track_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        trainStatus_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dev.katsute.onemta.MTARRProto.internal_static_transit_realtime_MtaRailroadStopTimeUpdate_descriptor;
      }

      @java.lang.Override
      public dev.katsute.onemta.MTARRProto.MtaRailroadStopTimeUpdate getDefaultInstanceForType() {
        return dev.katsute.onemta.MTARRProto.MtaRailroadStopTimeUpdate.getDefaultInstance();
      }

      @java.lang.Override
      public dev.katsute.onemta.MTARRProto.MtaRailroadStopTimeUpdate build() {
        dev.katsute.onemta.MTARRProto.MtaRailroadStopTimeUpdate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dev.katsute.onemta.MTARRProto.MtaRailroadStopTimeUpdate buildPartial() {
        dev.katsute.onemta.MTARRProto.MtaRailroadStopTimeUpdate result = new dev.katsute.onemta.MTARRProto.MtaRailroadStopTimeUpdate(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.track_ = track_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.trainStatus_ = trainStatus_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      private int bitField0_;

      private java.lang.Object track_ = "";
      /**
       * <code>optional string track = 1;</code>
       * @return Whether the track field is set.
       */
      public boolean hasTrack() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string track = 1;</code>
       * @return The track.
       */
      public java.lang.String getTrack() {
        java.lang.Object ref = track_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            track_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string track = 1;</code>
       * @return The bytes for track.
       */
      public com.google.protobuf.ByteString
          getTrackBytes() {
        java.lang.Object ref = track_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          track_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string track = 1;</code>
       * @param value The track to set.
       * @return This builder for chaining.
       */
      public Builder setTrack(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        track_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string track = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTrack() {
        bitField0_ = (bitField0_ & ~0x00000001);
        track_ = getDefaultInstance().getTrack();
        onChanged();
        return this;
      }
      /**
       * <code>optional string track = 1;</code>
       * @param value The bytes for track to set.
       * @return This builder for chaining.
       */
      public Builder setTrackBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        track_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object trainStatus_ = "";
      /**
       * <code>optional string trainStatus = 2;</code>
       * @return Whether the trainStatus field is set.
       */
      public boolean hasTrainStatus() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string trainStatus = 2;</code>
       * @return The trainStatus.
       */
      public java.lang.String getTrainStatus() {
        java.lang.Object ref = trainStatus_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            trainStatus_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string trainStatus = 2;</code>
       * @return The bytes for trainStatus.
       */
      public com.google.protobuf.ByteString
          getTrainStatusBytes() {
        java.lang.Object ref = trainStatus_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          trainStatus_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string trainStatus = 2;</code>
       * @param value The trainStatus to set.
       * @return This builder for chaining.
       */
      public Builder setTrainStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        trainStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string trainStatus = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTrainStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        trainStatus_ = getDefaultInstance().getTrainStatus();
        onChanged();
        return this;
      }
      /**
       * <code>optional string trainStatus = 2;</code>
       * @param value The bytes for trainStatus to set.
       * @return This builder for chaining.
       */
      public Builder setTrainStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        trainStatus_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:transit_realtime.MtaRailroadStopTimeUpdate)
    }

    // @@protoc_insertion_point(class_scope:transit_realtime.MtaRailroadStopTimeUpdate)
    private static final dev.katsute.onemta.MTARRProto.MtaRailroadStopTimeUpdate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dev.katsute.onemta.MTARRProto.MtaRailroadStopTimeUpdate();
    }

    public static dev.katsute.onemta.MTARRProto.MtaRailroadStopTimeUpdate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MtaRailroadStopTimeUpdate>
        PARSER = new com.google.protobuf.AbstractParser<MtaRailroadStopTimeUpdate>() {
      @java.lang.Override
      public MtaRailroadStopTimeUpdate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(
                  builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MtaRailroadStopTimeUpdate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MtaRailroadStopTimeUpdate> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dev.katsute.onemta.MTARRProto.MtaRailroadStopTimeUpdate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MtaRailroadCarriageDetailsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:transit_realtime.MtaRailroadCarriageDetails)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *Indicates the number of bikes permitted per carriage.
     *0=bikes prohibited, -1=No limit.
     * </pre>
     *
     * <code>optional int32 bicycles_allowed = 1 [default = 0];</code>
     * @return Whether the bicyclesAllowed field is set.
     */
    boolean hasBicyclesAllowed();
    /**
     * <pre>
     *Indicates the number of bikes permitted per carriage.
     *0=bikes prohibited, -1=No limit.
     * </pre>
     *
     * <code>optional int32 bicycles_allowed = 1 [default = 0];</code>
     * @return The bicyclesAllowed.
     */
    int getBicyclesAllowed();

    /**
     * <pre>
     *A description of the carriage type/model.
     * </pre>
     *
     * <code>optional string carriage_class = 2;</code>
     * @return Whether the carriageClass field is set.
     */
    boolean hasCarriageClass();
    /**
     * <pre>
     *A description of the carriage type/model.
     * </pre>
     *
     * <code>optional string carriage_class = 2;</code>
     * @return The carriageClass.
     */
    java.lang.String getCarriageClass();
    /**
     * <pre>
     *A description of the carriage type/model.
     * </pre>
     *
     * <code>optional string carriage_class = 2;</code>
     * @return The bytes for carriageClass.
     */
    com.google.protobuf.ByteString
        getCarriageClassBytes();

    /**
     * <code>optional .transit_realtime.MtaRailroadCarriageDetails.QuietCarriage quiet_carriage = 3 [default = UNKNOWN_QUIET_CARRIAGE];</code>
     * @return Whether the quietCarriage field is set.
     */
    boolean hasQuietCarriage();
    /**
     * <code>optional .transit_realtime.MtaRailroadCarriageDetails.QuietCarriage quiet_carriage = 3 [default = UNKNOWN_QUIET_CARRIAGE];</code>
     * @return The quietCarriage.
     */
    dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails.QuietCarriage getQuietCarriage();

    /**
     * <code>optional .transit_realtime.MtaRailroadCarriageDetails.ToiletFacilities toilet_facilities = 4 [default = UNKNOWN_TOILET_FACILITIES];</code>
     * @return Whether the toiletFacilities field is set.
     */
    boolean hasToiletFacilities();
    /**
     * <code>optional .transit_realtime.MtaRailroadCarriageDetails.ToiletFacilities toilet_facilities = 4 [default = UNKNOWN_TOILET_FACILITIES];</code>
     * @return The toiletFacilities.
     */
    dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails.ToiletFacilities getToiletFacilities();
  }
  /**
   * Protobuf type {@code transit_realtime.MtaRailroadCarriageDetails}
   */
  public static final class MtaRailroadCarriageDetails extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:transit_realtime.MtaRailroadCarriageDetails)
      MtaRailroadCarriageDetailsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MtaRailroadCarriageDetails.newBuilder() to construct.
    private MtaRailroadCarriageDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MtaRailroadCarriageDetails() {
      carriageClass_ = "";
      quietCarriage_ = 0;
      toiletFacilities_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MtaRailroadCarriageDetails();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.katsute.onemta.MTARRProto.internal_static_transit_realtime_MtaRailroadCarriageDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.katsute.onemta.MTARRProto.internal_static_transit_realtime_MtaRailroadCarriageDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails.class, dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails.Builder.class);
    }

    /**
     * <pre>
     * Whether the carriage has toilet facilities onboard.
     * </pre>
     *
     * Protobuf enum {@code transit_realtime.MtaRailroadCarriageDetails.QuietCarriage}
     */
    public enum QuietCarriage
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * It is unknown if the carriage is designated as a quiet carriage.
       *  This is the default case.
       * </pre>
       *
       * <code>UNKNOWN_QUIET_CARRIAGE = 0;</code>
       */
      UNKNOWN_QUIET_CARRIAGE(0),
      /**
       * <pre>
       * The carriage is designated a quiet carriage.
       * </pre>
       *
       * <code>QUIET_CARRIAGE = 1;</code>
       */
      QUIET_CARRIAGE(1),
      /**
       * <pre>
       * The carriage is not designated as a quiet carriage.
       * </pre>
       *
       * <code>NOT_QUIET_CARRIAGE = 2;</code>
       */
      NOT_QUIET_CARRIAGE(2),
      ;

      /**
       * <pre>
       * It is unknown if the carriage is designated as a quiet carriage.
       *  This is the default case.
       * </pre>
       *
       * <code>UNKNOWN_QUIET_CARRIAGE = 0;</code>
       */
      public static final int UNKNOWN_QUIET_CARRIAGE_VALUE = 0;
      /**
       * <pre>
       * The carriage is designated a quiet carriage.
       * </pre>
       *
       * <code>QUIET_CARRIAGE = 1;</code>
       */
      public static final int QUIET_CARRIAGE_VALUE = 1;
      /**
       * <pre>
       * The carriage is not designated as a quiet carriage.
       * </pre>
       *
       * <code>NOT_QUIET_CARRIAGE = 2;</code>
       */
      public static final int NOT_QUIET_CARRIAGE_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static QuietCarriage valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static QuietCarriage forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN_QUIET_CARRIAGE;
          case 1: return QUIET_CARRIAGE;
          case 2: return NOT_QUIET_CARRIAGE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<QuietCarriage>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          QuietCarriage> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<QuietCarriage>() {
              public QuietCarriage findValueByNumber(int number) {
                return QuietCarriage.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails.getDescriptor().getEnumTypes().get(0);
      }

      private static final QuietCarriage[] VALUES = values();

      public static QuietCarriage valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private QuietCarriage(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:transit_realtime.MtaRailroadCarriageDetails.QuietCarriage)
    }

    /**
     * <pre>
     * Whether the carriage has toilet facilities onboard.
     * </pre>
     *
     * Protobuf enum {@code transit_realtime.MtaRailroadCarriageDetails.ToiletFacilities}
     */
    public enum ToiletFacilities
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * It is unknown if the carriage has toilet facilities. This is the
       * default case.
       * </pre>
       *
       * <code>UNKNOWN_TOILET_FACILITIES = 0;</code>
       */
      UNKNOWN_TOILET_FACILITIES(0),
      /**
       * <pre>
       * The carriage has toilet facilities onboard.
       * </pre>
       *
       * <code>TOILET_ONBOARD = 1;</code>
       */
      TOILET_ONBOARD(1),
      /**
       * <pre>
       * The carriage does not have toilet facilities onboard.
       * </pre>
       *
       * <code>NO_TOILET_ONBOARD = 2;</code>
       */
      NO_TOILET_ONBOARD(2),
      ;

      /**
       * <pre>
       * It is unknown if the carriage has toilet facilities. This is the
       * default case.
       * </pre>
       *
       * <code>UNKNOWN_TOILET_FACILITIES = 0;</code>
       */
      public static final int UNKNOWN_TOILET_FACILITIES_VALUE = 0;
      /**
       * <pre>
       * The carriage has toilet facilities onboard.
       * </pre>
       *
       * <code>TOILET_ONBOARD = 1;</code>
       */
      public static final int TOILET_ONBOARD_VALUE = 1;
      /**
       * <pre>
       * The carriage does not have toilet facilities onboard.
       * </pre>
       *
       * <code>NO_TOILET_ONBOARD = 2;</code>
       */
      public static final int NO_TOILET_ONBOARD_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ToiletFacilities valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static ToiletFacilities forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN_TOILET_FACILITIES;
          case 1: return TOILET_ONBOARD;
          case 2: return NO_TOILET_ONBOARD;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ToiletFacilities>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ToiletFacilities> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ToiletFacilities>() {
              public ToiletFacilities findValueByNumber(int number) {
                return ToiletFacilities.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails.getDescriptor().getEnumTypes().get(1);
      }

      private static final ToiletFacilities[] VALUES = values();

      public static ToiletFacilities valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ToiletFacilities(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:transit_realtime.MtaRailroadCarriageDetails.ToiletFacilities)
    }

    private int bitField0_;
    public static final int BICYCLES_ALLOWED_FIELD_NUMBER = 1;
    private int bicyclesAllowed_;
    /**
     * <pre>
     *Indicates the number of bikes permitted per carriage.
     *0=bikes prohibited, -1=No limit.
     * </pre>
     *
     * <code>optional int32 bicycles_allowed = 1 [default = 0];</code>
     * @return Whether the bicyclesAllowed field is set.
     */
    @java.lang.Override
    public boolean hasBicyclesAllowed() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *Indicates the number of bikes permitted per carriage.
     *0=bikes prohibited, -1=No limit.
     * </pre>
     *
     * <code>optional int32 bicycles_allowed = 1 [default = 0];</code>
     * @return The bicyclesAllowed.
     */
    @java.lang.Override
    public int getBicyclesAllowed() {
      return bicyclesAllowed_;
    }

    public static final int CARRIAGE_CLASS_FIELD_NUMBER = 2;
    private volatile java.lang.Object carriageClass_;
    /**
     * <pre>
     *A description of the carriage type/model.
     * </pre>
     *
     * <code>optional string carriage_class = 2;</code>
     * @return Whether the carriageClass field is set.
     */
    @java.lang.Override
    public boolean hasCarriageClass() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *A description of the carriage type/model.
     * </pre>
     *
     * <code>optional string carriage_class = 2;</code>
     * @return The carriageClass.
     */
    @java.lang.Override
    public java.lang.String getCarriageClass() {
      java.lang.Object ref = carriageClass_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          carriageClass_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *A description of the carriage type/model.
     * </pre>
     *
     * <code>optional string carriage_class = 2;</code>
     * @return The bytes for carriageClass.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCarriageClassBytes() {
      java.lang.Object ref = carriageClass_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        carriageClass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUIET_CARRIAGE_FIELD_NUMBER = 3;
    private int quietCarriage_;
    /**
     * <code>optional .transit_realtime.MtaRailroadCarriageDetails.QuietCarriage quiet_carriage = 3 [default = UNKNOWN_QUIET_CARRIAGE];</code>
     * @return Whether the quietCarriage field is set.
     */
    @java.lang.Override public boolean hasQuietCarriage() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .transit_realtime.MtaRailroadCarriageDetails.QuietCarriage quiet_carriage = 3 [default = UNKNOWN_QUIET_CARRIAGE];</code>
     * @return The quietCarriage.
     */
    @java.lang.Override public dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails.QuietCarriage getQuietCarriage() {
      @SuppressWarnings("deprecation")
      dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails.QuietCarriage result = dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails.QuietCarriage.valueOf(quietCarriage_);
      return result == null ? dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails.QuietCarriage.UNKNOWN_QUIET_CARRIAGE : result;
    }

    public static final int TOILET_FACILITIES_FIELD_NUMBER = 4;
    private int toiletFacilities_;
    /**
     * <code>optional .transit_realtime.MtaRailroadCarriageDetails.ToiletFacilities toilet_facilities = 4 [default = UNKNOWN_TOILET_FACILITIES];</code>
     * @return Whether the toiletFacilities field is set.
     */
    @java.lang.Override public boolean hasToiletFacilities() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .transit_realtime.MtaRailroadCarriageDetails.ToiletFacilities toilet_facilities = 4 [default = UNKNOWN_TOILET_FACILITIES];</code>
     * @return The toiletFacilities.
     */
    @java.lang.Override public dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails.ToiletFacilities getToiletFacilities() {
      @SuppressWarnings("deprecation")
      dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails.ToiletFacilities result = dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails.ToiletFacilities.valueOf(toiletFacilities_);
      return result == null ? dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails.ToiletFacilities.UNKNOWN_TOILET_FACILITIES : result;
    }

    public static dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code transit_realtime.MtaRailroadCarriageDetails}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:transit_realtime.MtaRailroadCarriageDetails)
        dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetailsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dev.katsute.onemta.MTARRProto.internal_static_transit_realtime_MtaRailroadCarriageDetails_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dev.katsute.onemta.MTARRProto.internal_static_transit_realtime_MtaRailroadCarriageDetails_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails.class, dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails.Builder.class);
      }

      // Construct using dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bicyclesAllowed_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        carriageClass_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        quietCarriage_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        toiletFacilities_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dev.katsute.onemta.MTARRProto.internal_static_transit_realtime_MtaRailroadCarriageDetails_descriptor;
      }

      @java.lang.Override
      public dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails getDefaultInstanceForType() {
        return dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails.getDefaultInstance();
      }

      @java.lang.Override
      public dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails build() {
        dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails buildPartial() {
        dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails result = new dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.bicyclesAllowed_ = bicyclesAllowed_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.carriageClass_ = carriageClass_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.quietCarriage_ = quietCarriage_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.toiletFacilities_ = toiletFacilities_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      private int bitField0_;

      private int bicyclesAllowed_ ;
      /**
       * <pre>
       *Indicates the number of bikes permitted per carriage.
       *0=bikes prohibited, -1=No limit.
       * </pre>
       *
       * <code>optional int32 bicycles_allowed = 1 [default = 0];</code>
       * @return Whether the bicyclesAllowed field is set.
       */
      @java.lang.Override
      public boolean hasBicyclesAllowed() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *Indicates the number of bikes permitted per carriage.
       *0=bikes prohibited, -1=No limit.
       * </pre>
       *
       * <code>optional int32 bicycles_allowed = 1 [default = 0];</code>
       * @return The bicyclesAllowed.
       */
      @java.lang.Override
      public int getBicyclesAllowed() {
        return bicyclesAllowed_;
      }
      /**
       * <pre>
       *Indicates the number of bikes permitted per carriage.
       *0=bikes prohibited, -1=No limit.
       * </pre>
       *
       * <code>optional int32 bicycles_allowed = 1 [default = 0];</code>
       * @param value The bicyclesAllowed to set.
       * @return This builder for chaining.
       */
      public Builder setBicyclesAllowed(int value) {
        bitField0_ |= 0x00000001;
        bicyclesAllowed_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Indicates the number of bikes permitted per carriage.
       *0=bikes prohibited, -1=No limit.
       * </pre>
       *
       * <code>optional int32 bicycles_allowed = 1 [default = 0];</code>
       * @return This builder for chaining.
       */
      public Builder clearBicyclesAllowed() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bicyclesAllowed_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object carriageClass_ = "";
      /**
       * <pre>
       *A description of the carriage type/model.
       * </pre>
       *
       * <code>optional string carriage_class = 2;</code>
       * @return Whether the carriageClass field is set.
       */
      public boolean hasCarriageClass() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *A description of the carriage type/model.
       * </pre>
       *
       * <code>optional string carriage_class = 2;</code>
       * @return The carriageClass.
       */
      public java.lang.String getCarriageClass() {
        java.lang.Object ref = carriageClass_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            carriageClass_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *A description of the carriage type/model.
       * </pre>
       *
       * <code>optional string carriage_class = 2;</code>
       * @return The bytes for carriageClass.
       */
      public com.google.protobuf.ByteString
          getCarriageClassBytes() {
        java.lang.Object ref = carriageClass_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          carriageClass_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *A description of the carriage type/model.
       * </pre>
       *
       * <code>optional string carriage_class = 2;</code>
       * @param value The carriageClass to set.
       * @return This builder for chaining.
       */
      public Builder setCarriageClass(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        carriageClass_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *A description of the carriage type/model.
       * </pre>
       *
       * <code>optional string carriage_class = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCarriageClass() {
        bitField0_ = (bitField0_ & ~0x00000002);
        carriageClass_ = getDefaultInstance().getCarriageClass();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *A description of the carriage type/model.
       * </pre>
       *
       * <code>optional string carriage_class = 2;</code>
       * @param value The bytes for carriageClass to set.
       * @return This builder for chaining.
       */
      public Builder setCarriageClassBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        carriageClass_ = value;
        onChanged();
        return this;
      }

      private int quietCarriage_ = 0;
      /**
       * <code>optional .transit_realtime.MtaRailroadCarriageDetails.QuietCarriage quiet_carriage = 3 [default = UNKNOWN_QUIET_CARRIAGE];</code>
       * @return Whether the quietCarriage field is set.
       */
      @java.lang.Override public boolean hasQuietCarriage() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional .transit_realtime.MtaRailroadCarriageDetails.QuietCarriage quiet_carriage = 3 [default = UNKNOWN_QUIET_CARRIAGE];</code>
       * @return The quietCarriage.
       */
      @java.lang.Override
      public dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails.QuietCarriage getQuietCarriage() {
        @SuppressWarnings("deprecation")
        dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails.QuietCarriage result = dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails.QuietCarriage.valueOf(quietCarriage_);
        return result == null ? dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails.QuietCarriage.UNKNOWN_QUIET_CARRIAGE : result;
      }
      /**
       * <code>optional .transit_realtime.MtaRailroadCarriageDetails.QuietCarriage quiet_carriage = 3 [default = UNKNOWN_QUIET_CARRIAGE];</code>
       * @param value The quietCarriage to set.
       * @return This builder for chaining.
       */
      public Builder setQuietCarriage(dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails.QuietCarriage value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        quietCarriage_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .transit_realtime.MtaRailroadCarriageDetails.QuietCarriage quiet_carriage = 3 [default = UNKNOWN_QUIET_CARRIAGE];</code>
       * @return This builder for chaining.
       */
      public Builder clearQuietCarriage() {
        bitField0_ = (bitField0_ & ~0x00000004);
        quietCarriage_ = 0;
        onChanged();
        return this;
      }

      private int toiletFacilities_ = 0;
      /**
       * <code>optional .transit_realtime.MtaRailroadCarriageDetails.ToiletFacilities toilet_facilities = 4 [default = UNKNOWN_TOILET_FACILITIES];</code>
       * @return Whether the toiletFacilities field is set.
       */
      @java.lang.Override public boolean hasToiletFacilities() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional .transit_realtime.MtaRailroadCarriageDetails.ToiletFacilities toilet_facilities = 4 [default = UNKNOWN_TOILET_FACILITIES];</code>
       * @return The toiletFacilities.
       */
      @java.lang.Override
      public dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails.ToiletFacilities getToiletFacilities() {
        @SuppressWarnings("deprecation")
        dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails.ToiletFacilities result = dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails.ToiletFacilities.valueOf(toiletFacilities_);
        return result == null ? dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails.ToiletFacilities.UNKNOWN_TOILET_FACILITIES : result;
      }
      /**
       * <code>optional .transit_realtime.MtaRailroadCarriageDetails.ToiletFacilities toilet_facilities = 4 [default = UNKNOWN_TOILET_FACILITIES];</code>
       * @param value The toiletFacilities to set.
       * @return This builder for chaining.
       */
      public Builder setToiletFacilities(dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails.ToiletFacilities value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        toiletFacilities_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .transit_realtime.MtaRailroadCarriageDetails.ToiletFacilities toilet_facilities = 4 [default = UNKNOWN_TOILET_FACILITIES];</code>
       * @return This builder for chaining.
       */
      public Builder clearToiletFacilities() {
        bitField0_ = (bitField0_ & ~0x00000008);
        toiletFacilities_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:transit_realtime.MtaRailroadCarriageDetails)
    }

    // @@protoc_insertion_point(class_scope:transit_realtime.MtaRailroadCarriageDetails)
    private static final dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails();
    }

    public static dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MtaRailroadCarriageDetails>
        PARSER = new com.google.protobuf.AbstractParser<MtaRailroadCarriageDetails>() {
      @java.lang.Override
      public MtaRailroadCarriageDetails parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(
                  builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MtaRailroadCarriageDetails> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MtaRailroadCarriageDetails> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int MTA_RAILROAD_STOP_TIME_UPDATE_FIELD_NUMBER = 1005;
  /**
   * <code>extend .transit_realtime.TripUpdate.StopTimeUpdate { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      dev.katsute.onemta.GTFSRealtimeProto.TripUpdate.StopTimeUpdate,
      dev.katsute.onemta.MTARRProto.MtaRailroadStopTimeUpdate> mtaRailroadStopTimeUpdate = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        dev.katsute.onemta.MTARRProto.MtaRailroadStopTimeUpdate.class,
        dev.katsute.onemta.MTARRProto.MtaRailroadStopTimeUpdate.getDefaultInstance());
  public static final int MTA_RAILROAD_CARRIAGE_DETAILS_FIELD_NUMBER = 1005;
  /**
   * <code>extend .transit_realtime.VehiclePosition.CarriageDetails { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      dev.katsute.onemta.GTFSRealtimeProto.VehiclePosition.CarriageDetails,
      dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails> mtaRailroadCarriageDetails = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails.class,
        dev.katsute.onemta.MTARRProto.MtaRailroadCarriageDetails.getDefaultInstance());
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_MtaRailroadStopTimeUpdate_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_MtaRailroadStopTimeUpdate_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transit_realtime_MtaRailroadCarriageDetails_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transit_realtime_MtaRailroadCarriageDetails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031gtfs-realtime-MTARR.proto\022\020transit_rea" +
      "ltime\032\023gtfs-realtime.proto\"?\n\031MtaRailroa" +
      "dStopTimeUpdate\022\r\n\005track\030\001 \001(\t\022\023\n\013trainS" +
      "tatus\030\002 \001(\t\"\351\003\n\032MtaRailroadCarriageDetai" +
      "ls\022\033\n\020bicycles_allowed\030\001 \001(\005:\0010\022\026\n\016carri" +
      "age_class\030\002 \001(\t\022j\n\016quiet_carriage\030\003 \001(\0162" +
      ":.transit_realtime.MtaRailroadCarriageDe" +
      "tails.QuietCarriage:\026UNKNOWN_QUIET_CARRI" +
      "AGE\022s\n\021toilet_facilities\030\004 \001(\0162=.transit" +
      "_realtime.MtaRailroadCarriageDetails.Toi" +
      "letFacilities:\031UNKNOWN_TOILET_FACILITIES" +
      "\"W\n\rQuietCarriage\022\032\n\026UNKNOWN_QUIET_CARRI" +
      "AGE\020\000\022\022\n\016QUIET_CARRIAGE\020\001\022\026\n\022NOT_QUIET_C" +
      "ARRIAGE\020\002\"\\\n\020ToiletFacilities\022\035\n\031UNKNOWN" +
      "_TOILET_FACILITIES\020\000\022\022\n\016TOILET_ONBOARD\020\001" +
      "\022\025\n\021NO_TOILET_ONBOARD\020\002:\200\001\n\035mta_railroad" +
      "_stop_time_update\022+.transit_realtime.Tri" +
      "pUpdate.StopTimeUpdate\030\355\007 \001(\0132+.transit_" +
      "realtime.MtaRailroadStopTimeUpdate:\207\001\n\035m" +
      "ta_railroad_carriage_details\0221.transit_r" +
      "ealtime.VehiclePosition.CarriageDetails\030" +
      "\355\007 \001(\0132,.transit_realtime.MtaRailroadCar" +
      "riageDetailsB\"\n\022dev.katsute.onemtaB\nMTAR" +
      "RProtoH\002"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          dev.katsute.onemta.GTFSRealtimeProto.getDescriptor(),
        });
    internal_static_transit_realtime_MtaRailroadStopTimeUpdate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_transit_realtime_MtaRailroadStopTimeUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_MtaRailroadStopTimeUpdate_descriptor,
        new java.lang.String[] { "Track", "TrainStatus", });
    internal_static_transit_realtime_MtaRailroadCarriageDetails_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_transit_realtime_MtaRailroadCarriageDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transit_realtime_MtaRailroadCarriageDetails_descriptor,
        new java.lang.String[] { "BicyclesAllowed", "CarriageClass", "QuietCarriage", "ToiletFacilities", });
    mtaRailroadStopTimeUpdate.internalInit(descriptor.getExtensions().get(0));
    mtaRailroadCarriageDetails.internalInit(descriptor.getExtensions().get(1));
    dev.katsute.onemta.GTFSRealtimeProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
