name: Bug Report
description: Report a bug
labels: [bug]
assignees: []
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Prerequisites
      description: |
        *If **all** checks are not passed then the issue will be closed.*
      options:
        - label: I have checked that no other similar issue already exists.
          required: true
        - label: I have checked that this issue is actually a bug and not a feature.
          required: true
        - label: I have checked [discussions](https://github.com/KatsuteDev/OneMTA/discussions).
          required: true
        - label: I have checked the [documentation](https://docs.katsute.dev/onemta).
          required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: |
        Operating system name and version.
      placeholder: |
        ex: Windows 10
    validations:
      required: true

  - type: input
    id: java-version
    attributes:
      label: Java Version
      description: |
        Java version.
      placeholder: |
        ex: Java 11
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Release Version
      description: |
        Release version or branch commit where the issue occurred. Do not write 'latest'.
      placeholder: |
        ex: 1.0.0, b594412
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Issue
      description: |
        Explain your issue, add any relevant stacktraces here.
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code
      description: |
        (optional) Add any relevant code so we can try and replicate the issue. Make sure to remove your token.
      render: Java
    validations:
      required: false
