name: Java CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

jobs:
  java_ci:
    name: Java CI
    uses: Katsute/Workflows/.github/workflows/java.ci.yml@main
    with:
      package: true
      report: true
    secrets:
      token: ${{ secrets.BOT }}
