name: Sinon[bot]
on:
  workflow_dispatch: {}
  label:
    types: [created, edited, deleted]
  issues:
    types: [opened, closed, reopened]
  issue_comment:
    types: [created]
  pull_request:
    branches: [main]
    types: [opened, closed, reopened]
  release:
    types: [created, published]

concurrency: event-handle

jobs:
  sinon:
    name: Sinon[bot]
    uses: Katsute/Workflows/.github/workflows/sinon.yml@main
    secrets:
      token: ${{ secrets.SINON }}